version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  webapi:
    image: ddawidziak/bhl22-delphic:api 
    container_name: webapi
    ports:
    - "80:8080"
volumes:
  data: {}