name: Release.CD

on:
  push:
    branches:
      - 'main'

env:
  IMAGE: ddawidziak/bhl22-delphic

jobs:
  build-push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |-
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build image
        run: |-
          docker build \
            -f "Dockerfile" \
            -t "$IMAGE:${GITHUB_SHA::7}" \
            -t "$IMAGE:api" \
            .
      - name: Push image
        run: |-
          docker push "$IMAGE:${GITHUB_SHA::7}"
          docker push "$IMAGE:api"